### PR TITLE
Pull Nifti-related fixes from upstream

### PR DESCRIPTION
**Pull request by ihnorton**
Ref https://github.com/BRAINSia/BRAINSTools/pull/356

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @ihnorton . Integrating these now.

**Comment by jcfr** [comment]
New branch: https://github.com/Slicer/BRAINSTools/tree/slicer-2017-11-29-v4.7.1-42ac3c3

(we could have simply used the last hash of BRAINSTools too ...)

Integrated in [r26676](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26676)

**Comment by ihnorton** [comment]
> (we could have simply used the last hash of BRAINSTools too ...)

Yeah, if I had push access here I would have just pushed the commits on the last branch since it didn't diverge other than these ;)

**Comment by ihnorton** [comment]
Thanks for integrating!

**Pull request closed without merging**
