### PR TITLE
BUG: fix FSLToNrrd mode from Slicer

### PR DESCRIPTION
**Pull request by ihnorton**
need to use 'fslNIFTIFile' explicitly set by file-picker.

  fixes https://issues.slicer.org/view.php?id=4463

### CODE REVIEW

**Comment by ihnorton** [comment]
cherry-pick from upstream: https://github.com/BRAINSia/BRAINSTools/pull/354

**Comment by ihnorton** [comment]
cc @jcfr

**Comment by jcfr** [comment]
Thanks. Fork updated. See https://github.com/Slicer/BRAINSTools/commit/66db91f6d9944a5f931a58a67e195e3986c1751b

**Comment by ihnorton** [comment]
Thank you!

**Comment by jcfr** [comment]
xref https://github.com/Slicer/Slicer/pull/836

**Pull request closed without merging**
